@startuml
entity Role {
    +user_id : Long
    role_id : Long
    role : String
}

entity User {
    +user_id : Long
    username : String
    email : String
    master_hash : String
    created_at : Instant
    updated_at : Instant
    isEnabled : Boolean
}

entity PasswordEntry {
    +entry_id : Long
    user_id : Long
    service_name : String
    url : String
    login : String
    password_encrypted : String
    created_at : Instant
    updated_at : Instant
}

entity AuditLog {
    +log_id : UUID
    user_id : UUID
    action : String
    timestamp : DateTime
    ip_address : String
}

entity RefreshToken {
    +key_id : Long
    prefix : String
    hashedToken : String
    expiresAt : Instant
    createdAt : Instant
}

entity PasswordGenSettings {
    +user_id : Long
    length : INT
    minNumOfSpecChars : INT
    minNumOfDigits : INT
    hasLowercase : Boolean
    hasUppercase : Boolean
    hasSpecial : Boolean
    hasDigits : Boolean
}

User ||--o{ RefreshToken : "has"
User ||--|| Role : "is"
User ||--o{ PasswordEntry : "owns"
User ||--o{ AuditLog : "triggers"
User ||--|| PasswordGenSettings : "configured by"
@enduml
